#!/bin/bash
set -ex

cd /usr/local/src/janus-gateway-%VERSION%

JANUS_HOME=/opt/td-janus

./autogen.sh
./configure \
    --disable-data-channels \
    --disable-mqtt \
    --disable-plugin-nosip \
    --disable-plugin-recordplay \
    --disable-plugin-sip \
    --disable-plugin-sipre \
    --disable-plugin-streaming \
    --disable-plugin-textroom \
    --disable-plugin-videocall \
    --disable-plugin-videoroom \
    --disable-plugin-voicemail \
    --disable-rabbitmq \
    --disable-rabbitmq-event-handler \
    --disable-rest \
    --disable-sample-event-handler \
    --disable-unix-sockets \
    --prefix=${JANUS_HOME}

make CFLAGS='-std=c99'
make install

echo "janus gateway %VERSION% installed to ${JANUS_HOME}"
