---
name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build AMD64 image
        run: |
          podman build --build-arg=BUILD_ARCH=amd64 -t pkgbuild .
      - name: Copy built AMD64 packages
        run: |
          mkdir --parents dist
          podman run -v ./dist:/mnt -it pkgbuild '/bin/bash' -c '/bin/cp /root/*.deb /mnt'
      - name: Try install
        run: |
          sudo apt install --yes ./dist/*amd64.deb
      - name: Build ARM64 image
        run: |
          podman build --build-arg=BUILD_ARCH=arm64 -t pkgbuild .
      - name: Copy built ARM64 packages
        run: |
          mkdir --parents dist
          podman run -v ./dist:/mnt -it pkgbuild '/bin/bash' -c '/bin/cp /root/*.deb /mnt'
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          REPOSITORY_NAME: tada-team/ppa
          TARGET_FOLDER: td-libvips-dev-dist
          FOLDER: dist
          SSH: true
          BRANCH: main
